#!/usr/bin/env python3
"""
gen_packets.py

Builds ITCH-style Add Order messages and the expected decode for each one,
then writes them as hex files the testbench reads with $readmemh.

    python3 py/gen_packets.py --n 64 --seed 1

Outputs:
    build/packets.hex   one byte per line, messages back to back
    build/expected.hex  eight 64-bit values per message, in field order
    build/params.vh     `define N_MSGS, so the testbench sizes arrays exactly

Corner cases are injected deliberately rather than left to chance, since
uniform random values almost never hit the boundaries that break a parser.
"""

import argparse
import os
import random
import struct

MSG_LEN = 36
FIELDS = ["stock_locate", "tracking_num", "timestamp",
          "order_ref", "side", "shares", "stock", "price"]


def build_message(f):
    """Pack a field dict into 36 big-endian bytes."""
    out = b"A"
    out += struct.pack(">H", f["stock_locate"])
    out += struct.pack(">H", f["tracking_num"])
    out += f["timestamp"].to_bytes(6, "big")
    out += struct.pack(">Q", f["order_ref"])
    out += bytes([f["side"]])
    out += struct.pack(">I", f["shares"])
    out += f["stock"]
    out += struct.pack(">I", f["price"])
    assert len(out) == MSG_LEN, len(out)
    return out


def symbol(name):
    """8 chars, space padded, as ITCH does it. Accepts str or raw bytes."""
    raw = name if isinstance(name, bytes) else name.encode("latin-1")
    return raw[:8].ljust(8, b" ")


def corner_cases():
    """Boundary values a random generator would essentially never produce."""
    return [
        # all zeros
        dict(stock_locate=0, tracking_num=0, timestamp=0, order_ref=0,
             side=ord("B"), shares=0, stock=symbol(""), price=0),
        # all ones, every field at max
        dict(stock_locate=0xFFFF, tracking_num=0xFFFF,
             timestamp=(1 << 48) - 1, order_ref=(1 << 64) - 1,
             side=ord("S"), shares=0xFFFFFFFF, stock=symbol("ZZZZZZZZ"),
             price=0xFFFFFFFF),
        # single bit set in the widest field, catches shift-register bugs
        dict(stock_locate=1, tracking_num=1, timestamp=1, order_ref=1,
             side=ord("B"), shares=1, stock=symbol("A"), price=1),
        # high bit only, catches sign or truncation errors
        dict(stock_locate=0x8000, tracking_num=0x8000,
             timestamp=1 << 47, order_ref=1 << 63,
             side=ord("S"), shares=0x80000000, stock=symbol(b"\x80"),
             price=0x80000000),
        # byte value that collides with the message type marker
        dict(stock_locate=0x4141, tracking_num=0x4141,
             timestamp=0x414141414141, order_ref=0x4141414141414141,
             side=ord("B"), shares=0x41414141, stock=symbol("AAAAAAAA"),
             price=0x41414141),
        # a realistic one, for readability in waveforms
        dict(stock_locate=1234, tracking_num=0, timestamp=34_200_000_000_000,
             side=ord("B"), order_ref=987654321, shares=100,
             stock=symbol("NVDA"), price=1_234_500),
    ]


def random_message(rng):
    return dict(
        stock_locate=rng.getrandbits(16),
        tracking_num=rng.getrandbits(16),
        timestamp=rng.getrandbits(48),
        order_ref=rng.getrandbits(64),
        side=ord(rng.choice("BS")),
        shares=rng.getrandbits(32),
        stock=symbol(rng.choice(["AAPL", "NVDA", "AMD", "INTC",
                                 "QCOM", "TSM", "AVGO", "MU"])),
        price=rng.getrandbits(32),
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=64, help="total messages")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default="build")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    msgs = corner_cases()
    while len(msgs) < args.n:
        msgs.append(random_message(rng))
    msgs = msgs[:args.n]

    os.makedirs(args.out, exist_ok=True)

    with open(os.path.join(args.out, "packets.hex"), "w") as fh:
        for m in msgs:
            for b in build_message(m):
                fh.write(f"{b:02x}\n")

    with open(os.path.join(args.out, "expected.hex"), "w") as fh:
        for m in msgs:
            fh.write(f"{m['stock_locate']:016x}\n")
            fh.write(f"{m['tracking_num']:016x}\n")
            fh.write(f"{m['timestamp']:016x}\n")
            fh.write(f"{m['order_ref']:016x}\n")
            fh.write(f"{m['side']:016x}\n")
            fh.write(f"{m['shares']:016x}\n")
            fh.write(f"{int.from_bytes(m['stock'], 'big'):016x}\n")
            fh.write(f"{m['price']:016x}\n")

    with open(os.path.join(args.out, "params.vh"), "w") as fh:
        fh.write("// generated by py/gen_packets.py, do not edit\n")
        fh.write(f"`define N_MSGS {len(msgs)}\n")

    print(f"wrote {len(msgs)} messages "
          f"({len(corner_cases())} corner cases, "
          f"{len(msgs) - len(corner_cases())} random) to {args.out}/")


if __name__ == "__main__":
    main()#!/usr/bin/env python3
"""
gen_packets.py

Builds ITCH-style Add Order messages and the expected decode for each one,
then writes them as hex files the testbench reads with $readmemh.

    python3 py/gen_packets.py --n 64 --seed 1

Outputs:
    build/packets.hex   one byte per line, messages back to back
    build/expected.hex  eight 64-bit values per message, in field order

Corner cases are injected deliberately rather than left to chance, since
uniform random values almost never hit the boundaries that break a parser.
"""

import argparse
import os
import random
import struct

MSG_LEN = 36
FIELDS = ["stock_locate", "tracking_num", "timestamp",
          "order_ref", "side", "shares", "stock", "price"]


def build_message(f):
    """Pack a field dict into 36 big-endian bytes."""
    out = b"A"
    out += struct.pack(">H", f["stock_locate"])
    out += struct.pack(">H", f["tracking_num"])
    out += f["timestamp"].to_bytes(6, "big")
    out += struct.pack(">Q", f["order_ref"])
    out += bytes([f["side"]])
    out += struct.pack(">I", f["shares"])
    out += f["stock"]
    out += struct.pack(">I", f["price"])
    assert len(out) == MSG_LEN, len(out)
    return out


def symbol(name):
    """8 chars, space padded, as ITCH does it. Accepts str or raw bytes."""
    raw = name if isinstance(name, bytes) else name.encode("latin-1")
    return raw[:8].ljust(8, b" ")


def corner_cases():
    """Boundary values a random generator would essentially never produce."""
    return [
        # all zeros
        dict(stock_locate=0, tracking_num=0, timestamp=0, order_ref=0,
             side=ord("B"), shares=0, stock=symbol(""), price=0),
        # all ones, every field at max
        dict(stock_locate=0xFFFF, tracking_num=0xFFFF,
             timestamp=(1 << 48) - 1, order_ref=(1 << 64) - 1,
             side=ord("S"), shares=0xFFFFFFFF, stock=symbol("ZZZZZZZZ"),
             price=0xFFFFFFFF),
        # single bit set in the widest field, catches shift-register bugs
        dict(stock_locate=1, tracking_num=1, timestamp=1, order_ref=1,
             side=ord("B"), shares=1, stock=symbol("A"), price=1),
        # high bit only, catches sign or truncation errors
        dict(stock_locate=0x8000, tracking_num=0x8000,
             timestamp=1 << 47, order_ref=1 << 63,
             side=ord("S"), shares=0x80000000, stock=symbol(b"\x80"),
             price=0x80000000),
        # byte value that collides with the message type marker
        dict(stock_locate=0x4141, tracking_num=0x4141,
             timestamp=0x414141414141, order_ref=0x4141414141414141,
             side=ord("B"), shares=0x41414141, stock=symbol("AAAAAAAA"),
             price=0x41414141),
        # a realistic one, for readability in waveforms
        dict(stock_locate=1234, tracking_num=0, timestamp=34_200_000_000_000,
             side=ord("B"), order_ref=987654321, shares=100,
             stock=symbol("NVDA"), price=1_234_500),
    ]


def random_message(rng):
    return dict(
        stock_locate=rng.getrandbits(16),
        tracking_num=rng.getrandbits(16),
        timestamp=rng.getrandbits(48),
        order_ref=rng.getrandbits(64),
        side=ord(rng.choice("BS")),
        shares=rng.getrandbits(32),
        stock=symbol(rng.choice(["AAPL", "NVDA", "AMD", "INTC",
                                 "QCOM", "TSM", "AVGO", "MU"])),
        price=rng.getrandbits(32),
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=64, help="total messages")
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--out", default="build")
    args = ap.parse_args()

    rng = random.Random(args.seed)
    msgs = corner_cases()
    while len(msgs) < args.n:
        msgs.append(random_message(rng))
    msgs = msgs[:args.n]

    os.makedirs(args.out, exist_ok=True)

    with open(os.path.join(args.out, "packets.hex"), "w") as fh:
        for m in msgs:
            for b in build_message(m):
                fh.write(f"{b:02x}\n")

    with open(os.path.join(args.out, "expected.hex"), "w") as fh:
        for m in msgs:
            fh.write(f"{m['stock_locate']:016x}\n")
            fh.write(f"{m['tracking_num']:016x}\n")
            fh.write(f"{m['timestamp']:016x}\n")
            fh.write(f"{m['order_ref']:016x}\n")
            fh.write(f"{m['side']:016x}\n")
            fh.write(f"{m['shares']:016x}\n")
            fh.write(f"{int.from_bytes(m['stock'], 'big'):016x}\n")
            fh.write(f"{m['price']:016x}\n")

    print(f"wrote {len(msgs)} messages "
          f"({len(corner_cases())} corner cases, "
          f"{len(msgs) - len(corner_cases())} random) to {args.out}/")


if __name__ == "__main__":
    main()
